const MESSAGES = {
  COMMANDS: {
    Dev: {
      CMD: {
        name: "cmd",
        aliases: ['cmd'],
        category: 'Dev',
        description: "Pour le dev",
        cooldown: 0.1,
        usage: '',
        exemple: '',
        isUserAdmin: false,
        permissions: true,
        raw: false,
        vanish: false,
        block: false,
      },
      TEST: {
        name: "test",
        aliases: ['sm'],
        category: 'Dev',
        description: "Pour le dev",
        cooldown: 0.1,
        usage: '',
        exemple: '',
        isUserAdmin: false,
        permissions: true,
        raw: false,
        vanish: false,
        block: false,
      },
      EVAL: {
        name: "eval",
        aliases: ['ev'],
        category: 'Dev',
        description: "Pour le dev",
        cooldown: 0.1,
        usage: 'du code',
        exemple: '',
        isUserAdmin: false,
        permissions: false,
        raw: true,
        vanish: false,
        block: false,
      }
    },
    Misc: {
      HELP: {
        name: "help",
        aliases: ['help'],
        category: 'Misc',
        description: "Renvoie une liste de commandes ou les informations sur une seule!",
        cooldown: 3,
        usage: '<nom de la commande>',
        exemple: '',
        isUserAdmin: false,
        permissions: false,
        raw: false,
        vanish: false,
        block: false,
      },
      INVITE: {
        name: "invite",
        aliases: ['inv'],
        category: 'Misc',
        description: "Renvoie une invitation du bot",
        cooldown: 0.1,
        usage: '',
        exemple: '',
        isUserAdmin: false,
        permissions: false,
        raw: false,
        vanish: false,
        block: false,
      },
    },
    Pronote: {
      EMPLOIDUTEMPS: {
        name: "emploidutemps",
        aliases: ['edt'],
        category: 'Pronote',
        description: "Renvoie l'emplois du temps du jour",
        cooldown: 3,
        usage: '<laps de temps de que tu veux voir>',
        exemple:'12/05/2020',
        isUserAdmin: false,
        permissions: false,
        raw: true,
        vanish: false,
        block: false,
      },
      DEVOIR: {
        name: "devoir",
        aliases: ['dvr'],
        category: 'Pronote',
        description: "Renvoie les devoirs",
        cooldown: 3,
        usage: '',
        exemple: '',
        isUserAdmin: false,
        permissions: false,
        raw: true,
        vanish: false,
        block: false,
      },
      LOGIN: {
        name: "login",
        aliases: ['log'],
        category: 'Pronote',
        description: "Sert à enregistrer ses identifiants et mots de passes toute les académies utilisable sont répértorier ici: `https://github.com/Litarvan/pronote-api`",
        cooldown: 3,
        usage: '<url pronote> <identifiant> <mot de passe> [Academie]',
        exemple: 'https://0250007x.index-education.net/pronote alban.girardi 123456789 ac-besancon',
        isUserAdmin: false,
        permissions: false,
        raw: true,
        vanish: true,
        block: false,
      },
      ACADEMIE: {
        name: "academie",
        aliases: ['aca', 'cas'],
        category: 'Pronote',
        description: "Sert à enregistrer ton academie. Toute les académies utilisable sont répértorier ici: `https://github.com/Litarvan/pronote-api`",
        cooldown: 3,
        usage: '<Academie>',
        exemple: 'ac-besancon',
        isUserAdmin: false,
        permissions: false,
        raw: true,
        vanish: true,
        block: false,
      },
      IDENTIFIANT: {
        name: "identifiant",
        aliases: ['id'],
        category: 'Pronote',
        description: "Sert à enregistrer ses identifiants",
        cooldown: 3,
        usage: '<identifiant>',
        exemple: 'alban.girardi',
        isUserAdmin: false,
        permissions: false,
        raw: true,
        vanish: true,
        block: false,
      },
      MOTDEPASSE: {
        name: "motdepasse",
        aliases: ['mdp'],
        category: 'Pronote',
        description: "Sert à enregistrer son mots de passes",
        cooldown: 3,
        usage: '<mot de passe>',
        exemple: 'tarteenpion1852*',
        isUserAdmin: false,
        permissions: false,
        raw: true,
        vanish: true,
        block: false,
      },
      URLPRONOTE: {
        name: "urlpronote",
        aliases: ['url'],
        category: 'Pronote',
        description: "Sert à enregistrer l'url pronote",
        cooldown: 3,
        usage: '<url pronote>',
        exemple: 'https://0250007x.index-education.net/pronote',
        isUserAdmin: false,
        permissions: false,
        raw: true,
        vanish: true,
        block: false,
      },
    }

  },
}

exports.MESSAGES = MESSAGES;